# Generated by Django 5.2.4 on 2025-07-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlergenicosRestricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Alergênico/Restrição',
                'verbose_name_plural': 'Alergênicos/Restrições',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Estoque Central, Estoque Cozinha 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade em unidade de medida padrão (kg, litros, etc.)', max_digits=10)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('alergias_restricoes', models.ManyToManyField(blank=True, related_name='ingredientes', to='nucleo.alergenicosrestricoes')),
                ('estoques', models.ManyToManyField(through='nucleo.IngredienteEstoque', to='nucleo.estoque')),
            ],
            options={
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='ingredienteestoque',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ingredientes'),
        ),
        migrations.CreateModel(
            name='ItemReabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pratos_imagens/')),
                ('ingredientes', models.ManyToManyField(related_name='pratos', to='nucleo.ingredientes')),
            ],
            options={
                'verbose_name_plural': 'Pratos',
            },
        ),
        migrations.CreateModel(
            name='Reabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reabastecimento', models.DateField()),
                ('horario', models.TimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reabastecimentos', to='nucleo.fornecedor')),
                ('ingredientes', models.ManyToManyField(through='nucleo.ItemReabastecimento', to='nucleo.ingredientes')),
            ],
        ),
        migrations.AddField(
            model_name='itemreabastecimento',
            name='reabastecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.reabastecimento'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='nucleo.cliente')),
                ('restaurante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='nucleo.restaurante')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ingredienteestoque',
            unique_together={('ingrediente', 'estoque')},
        ),
        migrations.AlterUniqueTogether(
            name='itemreabastecimento',
            unique_together={('reabastecimento', 'ingrediente')},
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(help_text='Ex: Almoço, Jantar', max_length=50)),
                ('dia', models.DateField()),
                ('pratos', models.ManyToManyField(related_name='cardapios_onde_aparece', to='nucleo.pratos')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='nucleo.restaurante')),
            ],
            options={
                'unique_together': {('refeicao', 'dia', 'restaurante')},
            },
        ),
    ]
